# Generated by Django 2.0.2 on 2018-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256)),
                ('car_model', models.CharField(max_length=256)),
                ('car_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Franchises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Smr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smr_pic', models.ImageField(upload_to='smr_pics')),
                ('name', models.CharField(max_length=256)),
                ('territory', models.CharField(max_length=256)),
                ('car', models.ForeignKey(on_delete='PROTECT', related_name='smrs', to='ourteam.Cars')),
                ('franchise', models.ForeignKey(on_delete='PROTECT', related_name='smrs', to='ourteam.Franchises')),
            ],
        ),
    ]
