# Generated by Django 2.0.2 on 2018-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchises',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
